# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Ramblings of me
description: Interests in transit politics, and often, the lack of them
github_username: alexshell

# Email and twitter are optional:
email: 
twitter_username: alextshell

theme: minima
plugins:
  - jekyll-feed

minima:
  skin: solarized-dark

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
